version: 2
updates:
  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "Binah-Arbitor"
    assignees:
      - "Binah-Arbitor"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for Android Gradle Plugin (requires careful testing)
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
      # Ignore major Kotlin updates (requires migration)
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "Binah-Arbitor"
    assignees:
      - "Binah-Arbitor"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"