name: Build Issue
description: APK 빌드 관련 문제 신고
title: "[BUILD] "
labels: ["bug", "build"]
body:
  - type: markdown
    attributes:
      value: |
        빌드 관련 문제를 신고해 주셔서 감사합니다. 
        문제를 빠르게 해결할 수 있도록 가능한 한 자세히 작성해 주세요.

  - type: dropdown
    id: build-type
    attributes:
      label: 빌드 유형
      description: 어떤 빌드에서 문제가 발생했나요?
      options:
        - GitHub Actions (자동 빌드)
        - 로컬 빌드 (gradlew)
        - Android Studio
        - 기타
    validations:
      required: true

  - type: dropdown
    id: build-variant
    attributes:
      label: 빌드 변형
      description: 어떤 빌드 변형에서 문제가 발생했나요?
      options:
        - Debug
        - Release
        - 둘 다
    validations:
      required: true

  - type: textarea
    id: error-description
    attributes:
      label: 문제 설명
      description: 발생한 문제에 대한 명확한 설명을 작성해 주세요.
      placeholder: 예) APK 빌드 중 특정 단계에서 오류 발생
    validations:
      required: true

  - type: textarea
    id: error-log
    attributes:
      label: 오류 로그
      description: 오류 메시지나 로그를 붙여넣어 주세요.
      render: shell
      placeholder: |
        Gradle 오류 메시지 또는 GitHub Actions 로그를 여기에 붙여넣어 주세요.

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      description: 빌드 환경에 대한 정보를 제공해 주세요.
      placeholder: |
        - OS: (예: Ubuntu 22.04, Windows 11, macOS 13)
        - JDK 버전: (예: OpenJDK 17)
        - Android Studio 버전: (해당 시)
        - Gradle 버전: (해당 시)
        - 기타 관련 정보

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 문제 해결에 도움이 될 수 있는 추가 정보나 스크린샷을 제공해 주세요.

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 최신 버전의 코드를 사용하고 있습니다.
          required: true
        - label: 기존 이슈에서 이 문제를 찾을 수 없었습니다.
          required: true
        - label: 로컬에서 `./gradlew clean`을 실행했습니다.
          required: false